# -*- coding: utf-8 -*-
"""customer_review_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NG6G9JMiw8i33vRAuRqtsrbsZPW2fFT
"""

import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

df=pd.read_csv("Restaurant_Reviews.tsv",sep='\t')

df.shape

df.head()

df['Liked'].value_counts()

# CLEANING
import re
df['Review'][5]

review=re.sub('[^a-zA-Z]',' ',df['Review'][5])
review=review.split()
review

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

all_stop=set(stopwords.words("english"))
all_stop

review = [word for word in review if word not in all_stop]  # remove stopwords
review

#STEMMING
from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()
review = [ps.stem(word) for word in review]

import re
cus_stop={'don',"don't",'ain','aren',"aren't",'couldn',"couldn't",'didn',"didn't","doesn't","hadn't",'hadn','hasn',"hasn't",'haven',"haven't",'isn',"isn't",
          'ma','mightn',"mightn't",'mustn',"mustn't",'needn',"needn't",'shan',"shan't",'no','nor','not','shouldn',"shouldn't",'wasn',"wasn't",'weren',"weren't",'won',"won't",'wouldn',"wouldn't"}

corpus = []
ps = PorterStemmer()
stop_words=set(stopwords.words("english")) - cus_stop

for i in range(len(df)):
  review=re.sub('[^a-zA-Z]',' ',df['Review'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if word not in stop_words]
  review=" ".join(review)
  corpus.append(review)

df['processed_review']=corpus
df.tail()

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=1500)
x=cv.fit_transform(corpus).toarray()  #INDEPENDENT VARIABLE
x.shape

y=df['Liked']  #DEPENDENT VARIABLE
y

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred=nb.predict(X_test)


accuracy_score(y_test,y_pred)

lr=LogisticRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)

accuracy_score(y_test,y_pred)

def preprocess_review(text):
    review = re.sub('[^a-zA-Z]', ' ', text)
    review = review.lower()
    review = review.split()

    ps = PorterStemmer()
    stop_words = set(stopwords.words("english")) - cus_stop

    review = [ps.stem(word) for word in review if word not in stop_words]
    return " ".join(review)

# TEST NEW REVIE
new_review = "The food was amazzing!"
processed = preprocess_review(new_review)

vector = cv.transform([processed]).toarray()

prediction = nb.predict(vector)

if prediction[0] == 1:
    print("Sentiment: Positive Review ")
else:
    print("Sentiment: Negative Review ")

